import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


import React from 'react'
import Navbar from './Navbar';
import { Box, Grid, Link, Paper, ThemeProvider, Typography, createTheme, makeStyles } from '@mui/material';
import { themeOptions } from './theme';
import { ApolloProvider } from '@apollo/client';

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={themeOptions}>
          <Navbar />
          {children}
          <Box
            component={"footer"}
            sx={{
              // display: "flex",

            }}>

            <FooterComponent />

          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}




const FooterComponent = () => {

  return (
    <Box sx={{
      // center
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    }}>
      <Box p={3} >
        <Box
          // transparent


          sx={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 2,
            maxWidth: {
              sm: undefined,
              md: "50vw",

            },


          }}>
          <Link href="https://www.kemdikbud.go.id/">
            <img alt="kemdikbud" src="https://uny.ac.id/sites/default/files/inline-images/logo-kemdikbud_0_0.png" height="71" width="71" />
          </Link>
          <Link href="https://www.uny.ac.id/">
            <img alt="universitas negeri yogyakarta" src="https://uny.ac.id/sites/default/files/inline-images/LOGO%20%281%29.png" height="68" width="67" />
          </Link>
          <Link href="https://kampusmerdeka.kemdikbud.go.id/">
            <img alt="kampus merdeka" src="https://uny.ac.id/sites/default/files/inline-images/kampus%20merdeka%20kecil_0.png" height="66" width="124" />
          </Link>
          <Link href="https://kedaireka.id/">
            <img alt="kedaireka" src="https://uny.ac.id/sites/default/files/inline-images/kedaireka%20ok.png" height="67" width="130" />
          </Link>
        </Box>

        <Box sx={{
          marginTop: "1rem",
        }}>
          <Typography variant="h6" component="strong">UNIVERSITAS NEGERI YOGYAKARTA</Typography>
          <Typography>Jl. Colombo No.1 Karangmalang Yogyakarta 55281</Typography>
          <Typography>Telp : 0274-586168 | +62274542185</Typography>
          <Typography>Email : rksiu@uny.ac.id</Typography>
        </Box>

        <Typography mt={2} >
          Jam Kerja : Senin - Kamis 07.30 - 16.00 WIB | Jum`at 07.30 - 14.30 WIB
        </Typography>
      </Box>
    </Box>
  );
}

